app/catalog/models.py
from app import db
from datetime import datetime

# PUBLICATION TABLE
class Publication(db.Model):
    __tablename__ = 'publication'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), nullable=False)

    def __init__(self, name):
        self.name = name

    def __repr__(self):
        return 'The Publisher is {}'.format(self.name)


# SONGS TABLE
class Song(db.Model):
    __tablename__ = 'song'


    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(500), nullable=False, index=True)
    singers = db.Column(db.String(600))
    avg_rating = db.Column(db.Float)
    song_lyricist = db.Column(db.String(400))
    image = db.Column(db.String(100), unique=True)
    music_director = db.Column(db.String(400))
    pub_date = db.Column(db.DateTime, default=datetime.utcnow())

    # ESTABLISH RELATIONSHIP
    pub_id = db.Column(db.Integer, db.ForeignKey('publication.id'))

    def __init__(self, title, singers, avg_rating, song_lyricist, image, music_director, pub_id):

        self.title = title
        self.singers = singers
        self.avg_rating = avg_rating
        self.song_lyricists = song_lyricist
        self.image = image
        self.music_director = music_director
        self.pub_id = pub_id

    def __repr__(self):
        return '{} by {}'.format(self.title, self.singers)

app/catalog/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField, FloatField
from wtforms.validators import DataRequired


class EditMusicForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    song_lyricist = StringField('Song lyricist', validators=[DataRequired()])
    music_director = StringField('Music director', validators=[DataRequired()])
    submit = SubmitField('Update')


class CreateMusicForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    singers = StringField('Singers', validators=[DataRequired()])
    avg_rating = FloatField('Rating', validators=[DataRequired()])
    song_lyricist = StringField('Song Lyricist', validators=[DataRequired()])
    img_url = StringField('Image', validators=[DataRequired()])
    music_director = StringField('Music director', validators=[DataRequired()])
    pub_id = IntegerField('PublisherID', validators=[DataRequired()])
    submit = SubmitField('Create')

app/catalog/__init__.py
# app/catalog/__init__.py

from flask import Blueprint

main = Blueprint('main', __name__,template_folder='templates')


from app.catalog import routes

app/catalog/routes.py
from app.catalog import main
from app import db
from app.catalog.models import Song, Publication
from flask import render_template, request, redirect, url_for, flash
from app.catalog.forms import EditMusicForm, CreateMusicForm
from flask_login import login_required


@main.route('/')
def display_songs():
    songs=Song.query.all()
    return render_template('home.html',songs=songs)
@main.route('/display/publisher/<publisher_id>')
def display_publisher(publisher_id):
    publisher = Publication.query.filter_by(id=publisher_id).first()
    publisher_songs = Song.query.filter_by(pub_id = publisher.id).all()

    return render_template('publisher.html', publisher=publisher, publisher_songs=publisher_songs)

@main.route('/song/delete/<song_id>', methods=['GET', 'POST'])
@login_required
def delete_song(song_id):
    song = Song.query.get(song_id)
    if request.method == 'POST':
        db.session.delete(song)
        db.session.commit()
        flash('Song deleted successfully')
        return redirect(url_for('main.display_songs'))
    return render_template('delete_book.html', song=song, song_id=song.id)

@main.route('/edit/song/<song_id>', methods=['GET', 'POST'])
@login_required
def edit_song(song_id):
    song = Song.query.get(song_id)
    form = EditMusicForm(obj=song)
    if form.validate_on_submit():
        song.title = form.title.data
        song.song_lyricist = form.song_lyricist.data
        song.music_director = form.music_director.data
        db.session.add(song)
        db.session.commit()
        flash('Song Edited Successfully')
        return redirect(url_for('main.display_songs'))
    return render_template('edit_book.html', form=form)


@main.route('/create/book/<pub_id>', methods=['GET', 'POST'])
@login_required
def create_song(pub_id):
    form = CreateMusicForm()
    form.pub_id.data = pub_id  # pre-populates pub_id
    if form.validate_on_submit():
        song = Song(title=form.title.data, singers=form.singers.data, avg_rating=form.avg_rating.data,
                    song_lyricist=form.song_lyricist.data, image=form.img_url.data, music_director=form.music_director.data,
                    pub_id=form.pub_id.data)
        db.session.add(song)
        db.session.commit()
        flash('Song added successfully')
        return redirect(url_for('main.display_publisher', publisher_id=pub_id))
    return render_template('create_book.html', form=form, pub_id=pub_id)

app/catalog/templates/create_book.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <h4 style="margin-left: 45px"> create a new song entry  </h4>
        <hr>
          {{ form.hidden_tag() }}
          {{ wtf.quick_form(form) }}
    </div>
{% endblock %}

app/catalog/templates/delete_book.html
<!--catalog/templates/delete_book.html-->

{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <h4 style="margin-left: 45px"> delete the song  ? </h4>
        <hr>
            <p style="margin-left: 45px">
                Song Id: {{ song.id }}<br>
                Title: {{ song.title }}<br>
                Singers: {{ song.singers }}
            </p>
        <br>
        <form action="" method="POST" style="margin-left: 45px">
            <button type="submit" class="btn btn-sm btn-primary"> delete </button>
        </form>
    </div>
{% endblock %}

app/catalog/templates/edit_book.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <h4 style="margin-left: 45px"> update this song </h4>
        <hr>
          {{ form.hidden_tag() }}
          {{ wtf.quick_form(form) }}
    </div>
{% endblock %}

app/catalog/templates/home.html
{% extends 'layout.html' %}
{% block content %}
    <div class="container songs">
        <div class="row">
        {% for song in songs %}
           <div class ="col-md-4">
           <img src ="static/img/{{song.image}}" alt ="song-img" height="200" width ="190" class="img-rounded">
            <h4> Title: {{ song.title }} </h4>
            <p> Singers: {{ song.singers }} </p>
            <p> song lyricist: {{ song.song_lyricist }} </p>
            <p> Average Rating: {{ song.avg_rating }} </p>
            <p>music director : {{ song.music_director }} </p>
               <p><a href="{{ url_for('main.display_publisher', publisher_id=song.pub_id) }}">Publisher ID: {{ song.pub_id }}</a></p>
               <span class="label label-success"><a href="{{ url_for('main.create_song', pub_id=song.pub_id) }}" style="color: floralwhite"> create </a></span>
             <span class="label label-primary"><a href="{{ url_for('main.edit_song', song_id=song.id) }}" style="color: floralwhite"> edit </a></span>
             <span class="label label-info"><a href="{{ url_for('main.delete_song', song_id=song.id) }}" style="color: floralwhite"> delete </a></span>
            <br>
           </div>
         {%endfor%}
        </div>
    </div>
{% endblock content %}

app/catalog/templates/layout.html
{% import "bootstrap/wtf.html" as wtf %}
<!DOCTYPE html>
<html lang="en">

    {# head #}
    {% block head %}
        <head>
            <title> Songs Inc </title>
            <meta charset="UTF-8">
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
            <link href="https://fonts.googleapis.com/css?family=Sansita" rel="stylesheet">
            <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
        </head>
    {% endblock head %}

    {# body #}
    {% block body %}
    <body>
    <div class="wrapper">
        {# navigation bar #}
        {% block navbar %}
        <nav class="navbar navbar-inverse">
            <div class="container">
                <a class="navbar-brand title" href="{{ url_for('main.display_songs') }}">Music Shop Around the Corner</a>

                <ul class="nav navbar-nav pull-right nav-list">
                    <li><a href="{{ url_for('main.display_songs') }}"> Home </a></li>
                    <li><a href="{{ url_for('authentication.register_user') }}""> Register </a></li>
                    <li>

                        {% if current_user.is_authenticated %}
                            <a href="{{ url_for('authentication.log_out_user') }}"> SignOut </a>
                        {% else %}
                            <a href="{{ url_for('authentication.do_the_login') }}"> SignIn </a>
                        {% endif %}
                    </li>

                    <li>
                        <a href="">
                            {%  if current_user.is_authenticated %}
                                LoggedIn as <b style="color: deeppink">{{ current_user.user_name.title() }}</b>
                            {% else %}
                                Not LoggedIn
                            {% endif %}
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
        {% endblock navbar %}

        {# flash messaging #}
        {% for message in get_flashed_messages() %}
            <div class="container alert alert-info">
                <button type="button" class="close" data-dismiss="alert"></button>
                {{ message }}
            </div>
        {% endfor %}


        {# empty block for custom content #}
        {% block content %} {% endblock content %}

        {# footer #}
        {% block footer %}
        <footer>
            <div class="container ftr">
                <hr>
                <p class="text-center small"> The Shop Around The Corner &copy;	| 2019 </p>
            </div>
        </footer>
        {% endblock footer %}

    </div>
    </body>
    {% endblock body %}
</html>

app/catalog/templates/publisher.html
{% extends 'layout.html' %}

 {% block content%}
 <div class = "container publisher">
    <h4> Songs by {{ publisher.name }} </h4>
    <ol>
        {% for song in publisher_songs %}
            <li type="1">
                {{ song.title }} by {{ song.singers }}
            </li>
        {% endfor %}
    </ol>
 </div>>
{% endblock content %}